spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ecommerce-optic
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
